import type { Product } from "../types/product";

const products: Product[] = [
  {
    id: 1,
    title: "Wireless Headphones",
    description: "Premium wireless headphones with noise cancellation and deep bass.",
    price: 79.99,
    category: "Electronics",
    image: "https://picsum.photos/seed/headphones/400/400",
    rating: 4.5,
    stock: 25,
  },
  {
    id: 2,
    title: "Smart Watch",
    description: "Modern smartwatch with fitness tracking, notifications, and heart-rate monitoring.",
    price: 129.99,
    category: "Electronics",
    image: "https://picsum.photos/seed/smartwatch/400/400",
    rating: 4.4,
    stock: 18,
  },
  {
    id: 3,
    title: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with powerful sound and long battery life.",
    price: 49.99,
    category: "Electronics",
    image: "https://picsum.photos/seed/speaker/400/400",
    rating: 4.3,
    stock: 32,
  },
  {
    id: 4,
    title: "Mechanical Keyboard",
    description: "RGB mechanical keyboard designed for gaming and productivity.",
    price: 89.99,
    category: "Electronics",
    image: "https://picsum.photos/seed/keyboard/400/400",
    rating: 4.7,
    stock: 15,
  },
  {
    id: 5,
    title: "Wireless Mouse",
    description: "Ergonomic wireless mouse with adjustable DPI and silent clicks.",
    price: 29.99,
    category: "Electronics",
    image: "https://picsum.photos/seed/mouse/400/400",
    rating: 4.2,
    stock: 40,
  },
  {
    id: 6,
    title: "USB-C Hub",
    description: "Multi-port USB-C hub with HDMI, USB 3.0, and SD card support.",
    price: 39.99,
    category: "Electronics",
    image: "https://picsum.photos/seed/usbhub/400/400",
    rating: 4.1,
    stock: 28,
  },
  {
    id: 7,
    title: "Laptop Stand",
    description: "Adjustable aluminum laptop stand for comfortable working.",
    price: 34.99,
    category: "Electronics",
    image: "https://picsum.photos/seed/laptopstand/400/400",
    rating: 4.6,
    stock: 22,
  },
  {
    id: 8,
    title: "Webcam Full HD",
    description: "1080p webcam with built-in microphone for video calls and streaming.",
    price: 59.99,
    category: "Electronics",
    image: "https://picsum.photos/seed/webcam/400/400",
    rating: 4.3,
    stock: 20,
  },
  {
    id: 9,
    title: "Power Bank 20000mAh",
    description: "High-capacity power bank with fast charging and dual USB outputs.",
    price: 44.99,
    category: "Electronics",
    image: "https://picsum.photos/seed/powerbank/400/400",
    rating: 4.5,
    stock: 35,
  },
  {
    id: 10,
    title: "Wireless Charger",
    description: "Fast wireless charging pad compatible with modern smartphones.",
    price: 24.99,
    category: "Electronics",
    image: "https://picsum.photos/seed/charger/400/400",
    rating: 4.2,
    stock: 45,
  },

  {
    id: 11,
    title: "Classic T-Shirt",
    description: "Comfortable cotton t-shirt suitable for everyday wear.",
    price: 19.99,
    category: "Clothing",
    image: "https://picsum.photos/seed/tshirt/400/400",
    rating: 4.3,
    stock: 60,
  },
  {
    id: 12,
    title: "Slim Fit Jeans",
    description: "Modern slim-fit jeans made from durable stretch denim.",
    price: 49.99,
    category: "Clothing",
    image: "https://picsum.photos/seed/jeans/400/400",
    rating: 4.4,
    stock: 35,
  },
  {
    id: 13,
    title: "Hooded Sweatshirt",
    description: "Warm and comfortable hoodie perfect for casual outfits.",
    price: 39.99,
    category: "Clothing",
    image: "https://picsum.photos/seed/hoodie/400/400",
    rating: 4.6,
    stock: 30,
  },
  {
    id: 14,
    title: "Denim Jacket",
    description: "Classic denim jacket with a timeless casual design.",
    price: 69.99,
    category: "Clothing",
    image: "https://picsum.photos/seed/jacket/400/400",
    rating: 4.5,
    stock: 20,
  },
  {
    id: 15,
    title: "Casual Polo Shirt",
    description: "Classic polo shirt made from breathable cotton fabric.",
    price: 29.99,
    category: "Clothing",
    image: "https://picsum.photos/seed/polo/400/400",
    rating: 4.2,
    stock: 42,
  },
  {
    id: 16,
    title: "Formal Dress Shirt",
    description: "Elegant formal shirt suitable for business and special occasions.",
    price: 44.99,
    category: "Clothing",
    image: "https://picsum.photos/seed/dressshirt/400/400",
    rating: 4.4,
    stock: 27,
  },
  {
    id: 17,
    title: "Winter Coat",
    description: "Insulated winter coat designed to keep you warm in cold weather.",
    price: 119.99,
    category: "Clothing",
    image: "https://picsum.photos/seed/wintercoat/400/400",
    rating: 4.7,
    stock: 12,
  },
  {
    id: 18,
    title: "Sports Shorts",
    description: "Lightweight sports shorts designed for workouts and running.",
    price: 24.99,
    category: "Clothing",
    image: "https://picsum.photos/seed/shorts/400/400",
    rating: 4.1,
    stock: 38,
  },

  {
    id: 19,
    title: "Running Shoes",
    description: "Lightweight running shoes with responsive cushioning.",
    price: 89.99,
    category: "Shoes",
    image: "https://picsum.photos/seed/runningshoes/400/400",
    rating: 4.6,
    stock: 24,
  },
  {
    id: 20,
    title: "Casual Sneakers",
    description: "Comfortable everyday sneakers with a modern minimalist design.",
    price: 69.99,
    category: "Shoes",
    image: "https://picsum.photos/seed/sneakers/400/400",
    rating: 4.4,
    stock: 31,
  },
  {
    id: 21,
    title: "Leather Boots",
    description: "Durable leather boots designed for everyday outdoor use.",
    price: 109.99,
    category: "Shoes",
    image: "https://picsum.photos/seed/boots/400/400",
    rating: 4.7,
    stock: 14,
  },
  {
    id: 22,
    title: "Sports Sneakers",
    description: "Performance sneakers designed for training and gym workouts.",
    price: 79.99,
    category: "Shoes",
    image: "https://picsum.photos/seed/sportshoes/400/400",
    rating: 4.3,
    stock: 26,
  },
  {
    id: 23,
    title: "Classic Loafers",
    description: "Elegant loafers suitable for formal and semi-formal occasions.",
    price: 84.99,
    category: "Shoes",
    image: "https://picsum.photos/seed/loafers/400/400",
    rating: 4.5,
    stock: 18,
  },
  {
    id: 24,
    title: "Canvas Sneakers",
    description: "Lightweight canvas sneakers with a classic casual look.",
    price: 54.99,
    category: "Shoes",
    image: "https://picsum.photos/seed/canvas/400/400",
    rating: 4.2,
    stock: 33,
  },

  {
    id: 25,
    title: "Leather Backpack",
    description: "Premium leather backpack with multiple compartments for daily use.",
    price: 79.99,
    category: "Accessories",
    image: "https://picsum.photos/seed/backpack/400/400",
    rating: 4.6,
    stock: 16,
  },
  {
    id: 26,
    title: "Travel Backpack",
    description: "Spacious travel backpack with laptop compartment and luggage strap.",
    price: 59.99,
    category: "Accessories",
    image: "https://picsum.photos/seed/travelbag/400/400",
    rating: 4.5,
    stock: 21,
  },
  {
    id: 27,
    title: "Leather Wallet",
    description: "Compact leather wallet with multiple card and cash slots.",
    price: 29.99,
    category: "Accessories",
    image: "https://picsum.photos/seed/wallet/400/400",
    rating: 4.4,
    stock: 50,
  },
  {
    id: 28,
    title: "Classic Wrist Watch",
    description: "Elegant analog wrist watch with a stainless steel case.",
    price: 99.99,
    category: "Accessories",
    image: "https://picsum.photos/seed/watch/400/400",
    rating: 4.6,
    stock: 17,
  },
  {
    id: 29,
    title: "Sunglasses",
    description: "Stylish sunglasses with UV protection and a lightweight frame.",
    price: 39.99,
    category: "Accessories",
    image: "https://picsum.photos/seed/sunglasses/400/400",
    rating: 4.3,
    stock: 29,
  },
  {
    id: 30,
    title: "Leather Belt",
    description: "Classic genuine leather belt suitable for formal and casual outfits.",
    price: 24.99,
    category: "Accessories",
    image: "https://picsum.photos/seed/belt/400/400",
    rating: 4.2,
    stock: 44,
  },

  {
    id: 31,
    title: "Coffee Maker",
    description: "Automatic coffee maker for brewing fresh coffee at home.",
    price: 89.99,
    category: "Home",
    image: "https://picsum.photos/seed/coffeemaker/400/400",
    rating: 4.5,
    stock: 13,
  },
  {
    id: 32,
    title: "Electric Kettle",
    description: "Fast-boiling electric kettle with automatic shut-off.",
    price: 39.99,
    category: "Home",
    image: "https://picsum.photos/seed/kettle/400/400",
    rating: 4.4,
    stock: 25,
  },
  {
    id: 33,
    title: "Table Lamp",
    description: "Modern LED table lamp with adjustable brightness.",
    price: 34.99,
    category: "Home",
    image: "https://picsum.photos/seed/lamp/400/400",
    rating: 4.3,
    stock: 20,
  },
  {
    id: 34,
    title: "Bedside Organizer",
    description: "Compact bedside organizer for keeping essentials within reach.",
    price: 22.99,
    category: "Home",
    image: "https://picsum.photos/seed/organizer/400/400",
    rating: 4.1,
    stock: 34,
  },
  {
    id: 35,
    title: "Decorative Wall Clock",
    description: "Modern wall clock that adds a stylish touch to any room.",
    price: 45.99,
    category: "Home",
    image: "https://picsum.photos/seed/wallclock/400/400",
    rating: 4.5,
    stock: 19,
  },
  {
    id: 36,
    title: "Kitchen Storage Set",
    description: "Set of reusable containers for organized kitchen storage.",
    price: 32.99,
    category: "Home",
    image: "https://picsum.photos/seed/storage/400/400",
    rating: 4.4,
    stock: 27,
  },

  {
    id: 37,
    title: "Yoga Mat",
    description: "Non-slip exercise mat suitable for yoga, stretching, and workouts.",
    price: 29.99,
    category: "Sports",
    image: "https://picsum.photos/seed/yogamat/400/400",
    rating: 4.6,
    stock: 35,
  },
  {
    id: 38,
    title: "Dumbbell Set",
    description: "Adjustable dumbbell set for strength training at home.",
    price: 69.99,
    category: "Sports",
    image: "https://picsum.photos/seed/dumbbells/400/400",
    rating: 4.5,
    stock: 12,
  },
  {
    id: 39,
    title: "Football",
    description: "Durable training football suitable for outdoor matches.",
    price: 24.99,
    category: "Sports",
    image: "https://picsum.photos/seed/football/400/400",
    rating: 4.4,
    stock: 30,
  },
  {
    id: 40,
    title: "Basketball",
    description: "Official-size basketball designed for indoor and outdoor courts.",
    price: 27.99,
    category: "Sports",
    image: "https://picsum.photos/seed/basketball/400/400",
    rating: 4.3,
    stock: 24,
  },
  {
    id: 41,
    title: "Resistance Bands",
    description: "Set of resistance bands for full-body strength and mobility workouts.",
    price: 19.99,
    category: "Sports",
    image: "https://picsum.photos/seed/bands/400/400",
    rating: 4.5,
    stock: 40,
  },
  {
    id: 42,
    title: "Gym Water Bottle",
    description: "Large reusable water bottle designed for workouts and sports.",
    price: 18.99,
    category: "Sports",
    image: "https://picsum.photos/seed/bottle/400/400",
    rating: 4.2,
    stock: 55,
  },

  {
    id: 43,
    title: "Facial Cleanser",
    description: "Gentle facial cleanser designed for daily skincare routines.",
    price: 16.99,
    category: "Beauty",
    image: "https://picsum.photos/seed/cleanser/400/400",
    rating: 4.4,
    stock: 45,
  },
  {
    id: 44,
    title: "Moisturizing Cream",
    description: "Daily moisturizing cream that helps keep skin hydrated.",
    price: 21.99,
    category: "Beauty",
    image: "https://picsum.photos/seed/moisturizer/400/400",
    rating: 4.5,
    stock: 38,
  },
  {
    id: 45,
    title: "Perfume",
    description: "Elegant long-lasting fragrance suitable for everyday use.",
    price: 59.99,
    category: "Beauty",
    image: "https://picsum.photos/seed/perfume/400/400",
    rating: 4.6,
    stock: 20,
  },
  {
    id: 46,
    title: "Hair Dryer",
    description: "Powerful hair dryer with multiple heat and speed settings.",
    price: 44.99,
    category: "Beauty",
    image: "https://picsum.photos/seed/hairdryer/400/400",
    rating: 4.3,
    stock: 22,
  },
  {
    id: 47,
    title: "Makeup Brush Set",
    description: "Professional makeup brush set with soft synthetic bristles.",
    price: 29.99,
    category: "Beauty",
    image: "https://picsum.photos/seed/makeup/400/400",
    rating: 4.5,
    stock: 31,
  },
  {
    id: 48,
    title: "Lip Balm Set",
    description: "Moisturizing lip balm set with multiple refreshing flavors.",
    price: 12.99,
    category: "Beauty",
    image: "https://picsum.photos/seed/lipbalm/400/400",
    rating: 4.2,
    stock: 60,
  },

  {
    id: 49,
    title: "Travel Suitcase",
    description: "Durable hard-shell suitcase with wheels and expandable storage.",
    price: 109.99,
    category: "Travel",
    image: "https://picsum.photos/seed/suitcase/400/400",
    rating: 4.7,
    stock: 15,
  },
  {
    id: 50,
    title: "Travel Neck Pillow",
    description: "Memory foam travel pillow designed for comfortable long journeys.",
    price: 24.99,
    category: "Travel",
    image: "https://picsum.photos/seed/neckpillow/400/400",
    rating: 4.3,
    stock: 36,
  },
];

export default products;